### ISSUE TITLE
Neither xposed module nor lucky patcher works

### ISSUE THREAD

**Issue by pajacek89** [pylerSM/YouTubeBackgroundPlayback#308]
Hey. I can't make it works, no idea why. Can you take a look? When I block or take youtube to background stream is stopped. When I click play button in notification bar YT crashes.

```
7 mar 2017 21:39:02 UTC

Loading Xposed v54 (for Zygote)...

Running ROM 'KM_DRIVE_23122014_V1.4_ROOTED' with fingerprint 'Android/msm8x25q_d5/msm8x25q_d5:4.1.2/JZO54K/eng.android.20141223.174135:user/test-keys'

Loading modules from /data/app/com.pyler.youtubebackgroundplayback-1.apk

  Loading class com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback

Loading modules from /data/app/name.mikanoshi.yourtubeplus-1.apk

  Loading class name.mikanoshi.yourtubeplus.XposedMod

Loading modules from /data/app/ma.wanam.youtubeadaway-1.apk

  Loading class ma.wanam.youtubeadaway.Xposed

Loading modules from /data/app/com.android.vending.billing.InAppBillingService.LOCK-1.apk

  Loading class com.chelpus.XSupport

de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.WatchWhileActivity

	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)

	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)

	at name.mikanoshi.yourtubeplus.XposedMod.handleLoadPackage(XposedMod.java:57)

	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)

	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)

	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)

	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)

	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)

	at android.app.ActivityThread.handleBindApplication(Native Method)

	at android.app.ActivityThread.access$1300(ActivityThread.java:133)

	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1263)

	at android.os.Handler.dispatchMessage(Handler.java:99)

	at android.os.Looper.loop(Looper.java:137)

	at android.app.ActivityThread.main(ActivityThread.java:4794)

	at java.lang.reflect.Method.invokeNative(Native Method)

	at java.lang.reflect.Method.invoke(Method.java:511)

	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)

	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)

	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

	at dalvik.system.NativeStart.main(Native Method)

Caused by: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.WatchWhileActivity

	at java.lang.Class.classForName(Native Method)

	at java.lang.Class.forName(Class.java:217)

	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)

	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)

	... 19 more

Caused by: java.lang.NoClassDefFoundError: com/google/android/apps/youtube/app/WatchWhileActivity

	... 23 more

Caused by: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.WatchWhileActivity

	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)

	... 23 more

YouTube: com.google.android.youtube 12.05.53 loaded!

YouTube AdAway 3.5.0: Trying brute force way...

YouTube AdAway: Successfully hooked ads DB: srn

YouTube AdAway: Successfully hooked ows constructor!

YouTube AdAway: Successfully hooked ows param=nco

YouTube AdAway: Successfully hooked ad response: lmu

de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.WatchWhileActivity

	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)

	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)

	at name.mikanoshi.yourtubeplus.XposedMod.handleLoadPackage(XposedMod.java:57)

	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)

	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)

	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)

	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)

	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)

	at android.app.ActivityThread.handleBindApplication(Native Method)

	at android.app.ActivityThread.access$1300(ActivityThread.java:133)

	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1263)

	at android.os.Handler.dispatchMessage(Handler.java:99)

	at android.os.Looper.loop(Looper.java:137)

	at android.app.ActivityThread.main(ActivityThread.java:4794)

	at java.lang.reflect.Method.invokeNative(Native Method)

	at java.lang.reflect.Method.invoke(Method.java:511)

	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)

	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)

	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

	at dalvik.system.NativeStart.main(Native Method)

Caused by: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.WatchWhileActivity

	at java.lang.Class.classForName(Native Method)

	at java.lang.Class.forName(Class.java:217)

	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)

	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)

	... 19 more

Caused by: java.lang.NoClassDefFoundError: com/google/android/apps/youtube/app/WatchWhileActivity

	... 23 more

Caused by: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.WatchWhileActivity

	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)

	... 23 more

YouTube: com.google.android.youtube 12.05.53 loaded!

YouTube AdAway 3.5.0: Trying brute force way...

YouTube AdAway: Successfully hooked ads DB: srn

YouTube AdAway: Successfully hooked ows constructor!

YouTube AdAway: Successfully hooked ows param=nco

YouTube AdAway: Successfully hooked ad response: lmu
```

**Comment by pajacek89** [comment]
Still no progress, I can't make it working. Can dalvik be a problem?
