### ISSUE TITLE
Conflict with Youtube AdAway

### ISSUE THREAD

**Issue by bysteven** [pylerSM/YouTubeBackgroundPlayback#360]
Having both Youtube Background Play and Youtube AdAway active, the app will crash a few swconds after start. Both work well for themselves.

**Comment by benrap** [comment]
Can confirm.

**Comment by th3an7** [comment]
@bysteven @benrap Could you please check logs (Xposed and logcat) if they have any errors?

**Comment by Electricity2015** [comment]
I have YouTube 13.20.54 and works fine with both YouTube AdAway and YouTube Background Playback active

**Comment by benrap** [comment]
I've narrowed down the error logs so that just the errors we're looking for are there.

> 06-07 11:04:12.383 13887-14142/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: com.google.android.youtube, PID: 13887
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassCastException: apne cannot be cast to javax.net.ssl.HttpsURLConnection
        at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback$HooksDownloadTask.doInBackground(YouTubeBackgroundPlayback.java:266)
        at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback$HooksDownloadTask.doInBackground(YouTubeBackgroundPlayback.java:253)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
06-07 11:04:12.392 589-589/? E/SELinux: avc:  denied  { find } for service=opdiagnose pid=13887 uid=10091 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
06-07 11:04:12.393 589-589/? E/SELinux: avc:  denied  { find } for service=opdiagnose pid=13887 uid=10091 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
06-07 11:04:15.373 1482-2662/? E/ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
06-07 11:04:15.373 1482-2662/? E/ANDR-IOP: IOP HAL: Received pkg_name = com.google.android.youtube pid = -1
06-07 11:04:15.610 13778-14168/? E/zygote64: The String#value field is not present on Android versions >= 6.0
06-07 11:04:15.731 13778-14225/? E/GoogleConversionReporter: Error sending ping
    apmj: Exception in CronetUrlRequest: net::ERR_CONNECTION_REFUSED, ErrorCode=7, InternalErrorCode=-102, Retryable=false
        at org.chromium.net.impl.CronetUrlRequest.onError(SourceFile:141)
06-07 11:04:16.161 13778-13778/? E/YouTube: InteractionLoggingScreen is null.
06-07 11:04:16.197 13778-13778/? E/YouTube: InteractionLoggingScreen is null.
06-07 11:04:16.258 13778-13778/? E/tnx: No overlay to dismiss.
06-07 11:04:16.364 13778-14159/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: com.google.android.youtube, PID: 13778
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassCastException: apne cannot be cast to javax.net.ssl.HttpsURLConnection
        at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback$HooksDownloadTask.doInBackground(YouTubeBackgroundPlayback.java:266)
        at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback$HooksDownloadTask.doInBackground(YouTubeBackgroundPlayback.java:253)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
06-07 11:04:16.378 589-589/? E/SELinux: avc:  denied  { find } for service=opdiagnose pid=13778 uid=10091 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
    avc:  denied  { find } for service=opdiagnose pid=13778 uid=10091 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
06-07 11:04:16.413 13778-13778/? E/YouTube: InteractionLoggingScreen is null.
    InteractionLoggingScreen is null.
06-07 11:04:16.429 13778-13778/? E/YouTube: InteractionLoggingScreen is null.
06-07 11:04:16.430 13778-13778/? E/YouTube: InteractionLoggingScreen is null.

**Comment by bysteven** [comment]
@Electricity2015: What did you enable first?

**Comment by Electricity2015** [comment]
Both in the same time,try to do a soft reboot

**Comment by bysteven** [comment]
I tried it again with the newest Youtube version 13.20.54 and it works now.

**Comment by wolcano** [comment]
i get crashes too. is there recommended order of activating the xposed modules?
